In [1]:
import os
import subprocess
from dotenv import load_dotenv
from pathlib import Path

from collections import Counter

import pandas as pd

import deeparg
from Bio import SeqIO

from pprint import pprint
from tqdm.auto import tqdm

load_dotenv()

True

In [2]:
INPUT_DIR = "/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes"

In [3]:
file_extension_counts = Counter(os.path.splitext(f)[1].lower().lstrip(".") for root, dirs, files in os.walk(INPUT_DIR) for f in files)

pprint(file_extension_counts)

Counter({'faa': 641,
         'fna': 641,
         'gff': 640,
         'log': 640,
         'txt': 640,
         'tbl': 640,
         'fsa': 640,
         'gbk': 640,
         'ffn': 640,
         'sqn': 640,
         'tsv': 640,
         'err': 640})

| Extension | Meaning                  | Contains                                                                                                       |
| --------- | ------------------------ | -------------------------------------------------------------------------------------------------------------- |
| **.fna**  | FASTA Nucleotide         | Whole genome nucleotide sequences (assembled contigs/chromosomes/scaffolds)                                    |
| **.faa**  | FASTA Amino Acid         | Predicted protein sequences translated from CDS features                                                       |
| **.ffn**  | FASTA Feature Nucleotide | Nucleotide sequences of genes/CDS only (not the entire genome)                                                 |
| **.fsa**  | FASTA Sequence           | Generic FASTA file. Often used during submission workflows. Can contain nucleotide sequences similar to `.fna` |
| **.gff**  | General Feature Format   | Genome annotations: genes, CDS, tRNA, rRNA, coordinates, strands, attributes                                   |
| **.gbk**  | GenBank Format           | Sequence + annotations + metadata in one rich file                                                             |
| **.tbl**  | Feature Table            | NCBI annotation table used during genome submission                                                            |
| **.sqn**  | Sequin File              | Binary submission package used by NCBI's Sequin/BankIt submission system                                       |
| **.err**  | Error Log                | Validation or submission errors generated by annotation/submission software                                    |
| **.log**  | Log File                 | Program execution logs                                                                                         |
| **.tsv**  | Tab-Separated Values     | Annotation summaries, statistics, metadata tables                                                              |
| **.txt**  | Plain Text               | Notes, reports, readme files, miscellaneous output                                                             |

#### Relationship between the important biological files

<pre>
Genome assembly 
    |
    +-- genome.fna   (full nucleotide sequence)
    |
    +-- annotations.gff
    |
    +-- proteins.faa
    |
    +-- genes.ffn
    |
    +-- genome.gbk
</pre>

In [4]:
faa_files = [os.path.join(root, f) for root, dirs, files in os.walk(INPUT_DIR) for f in files if f.endswith(".faa")]
print("Unique .faa file types:", len(faa_files))

Unique .faa file types: 641

In [5]:
OUTPUT_DIR = "/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/"
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

In [6]:
filed = 0
filed_files = []
completed = 0
total = len(faa_files)

for faa_file in tqdm(faa_files):
    sample = os.path.splitext(os.path.basename(faa_file))[0]
    output_prefix = os.path.join(OUTPUT_DIR, sample)

    cmd = [
        "deeparg",
        "predict",
        "--model",
        "LS",
        "--type",
        "prot",
        "--input",
        faa_file,
        "--output",
        output_prefix,
    ]

    print("Running: " + " ".join(cmd))
    exit_code = subprocess.call(cmd)

    if exit_code != 0:
        filed += 1
        filed_files.append(faa_file)
        print("FAILED: " + faa_file)
    else:
        completed += 1
        print("COMPLETED: " + faa_file)
    print(f"Total: {total}, Completed: {completed}, Failed: {filed}")

  0%|          | 0/641 [00:00<?, ?it/s]

Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A9/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A9/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A9/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 272
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 25010.76it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A9/bin.1/bin.1.faa
Total: 641, Completed: 1, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A9/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A9/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A9/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 631
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13503.88it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A9/bin.13/bin.13.faa
Total: 641, Completed: 2, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A9/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A9/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A9/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1393
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 48998.88it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A9/bin.20/bin.20.faa
Total: 641, Completed: 3, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 724
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 34923.43it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.8/bin.8.faa
Total: 641, Completed: 4, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 293
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9700.06it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.10/bin.10.faa
Total: 641, Completed: 5, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 573
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.002s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 50472.97it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.22/bin.22.faa
Total: 641, Completed: 6, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 6
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14543.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.26/bin.26.faa
Total: 641, Completed: 7, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.27/bin.27.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.27/bin.27.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.27/bin.27.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 292
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 22040.48it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.27/bin.27.faa
Total: 641, Completed: 8, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11851.66it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.13/bin.13.faa
Total: 641, Completed: 9, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 603
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57065.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.2/bin.2.faa
Total: 641, Completed: 10, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.28/bin.28.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.28/bin.28.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.28/bin.28.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 53
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19972.88it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.28/bin.28.faa
Total: 641, Completed: 11, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.31/bin.31.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.31/bin.31.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.31/bin.31.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 154
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10991.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.31/bin.31.faa
Total: 641, Completed: 12, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.23/bin.23.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.23/bin.23.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.23/bin.23.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8958.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.23/bin.23.faa
Total: 641, Completed: 13, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.34/bin.34.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.34/bin.34.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.34/bin.34.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55115.69it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.34/bin.34.faa
Total: 641, Completed: 14, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 700
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58908.76it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G5/bin.14/bin.14.faa
Total: 641, Completed: 15, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53025.34it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.8/bin.8.faa
Total: 641, Completed: 16, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 292
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11397.57it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.18/bin.18.faa
Total: 641, Completed: 17, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 47825.59it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.1/bin.1.faa
Total: 641, Completed: 18, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.30/bin.30.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.30/bin.30.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.30/bin.30.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 81
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 32742.42it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.30/bin.30.faa
Total: 641, Completed: 19, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8573.80it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.25/bin.25.faa
Total: 641, Completed: 20, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58497.96it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H7/bin.20/bin.20.faa
Total: 641, Completed: 21, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B4/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B4/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B4/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 294
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7720.05it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B4/bin.5/bin.5.faa
Total: 641, Completed: 22, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B4/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B4/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B4/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 23
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57614.07it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B4/bin.9/bin.9.faa
Total: 641, Completed: 23, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 531
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17660.23it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.1/bin.1.faa
Total: 641, Completed: 24, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 291
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 22647.43it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.12/bin.12.faa
Total: 641, Completed: 25, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.28/bin.28.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.28/bin.28.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.28/bin.28.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56603.29it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.28/bin.28.faa
Total: 641, Completed: 26, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 397
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57221.06it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.25/bin.25.faa
Total: 641, Completed: 27, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.29/bin.29.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.29/bin.29.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.29/bin.29.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 294
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12941.39it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.29/bin.29.faa
Total: 641, Completed: 28, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 144
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 18783.27it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.11/bin.11.faa
Total: 641, Completed: 29, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.23/bin.23.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.23/bin.23.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.23/bin.23.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 292
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 45491.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.23/bin.23.faa
Total: 641, Completed: 30, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 53
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15038.74it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A12/bin.20/bin.20.faa
Total: 641, Completed: 31, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1325
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17855.70it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.4/bin.4.faa
Total: 641, Completed: 32, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 218
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9724.79it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.12/bin.12.faa
Total: 641, Completed: 33, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 532
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58743.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.20/bin.20.faa
Total: 641, Completed: 34, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 122
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58254.22it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F5/bin.24/bin.24.faa
Total: 641, Completed: 35, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0.001s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2749
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.002s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55775.32it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.16/bin.16.faa
Total: 641, Completed: 36, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 638
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17593.56it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.10/bin.10.faa
Total: 641, Completed: 37, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9666.52it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.22/bin.22.faa
Total: 641, Completed: 38, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 43
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15893.54it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.1/bin.1.faa
Total: 641, Completed: 39, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.30/bin.30.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.30/bin.30.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.30/bin.30.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 55
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8598.41it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.30/bin.30.faa
Total: 641, Completed: 40, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 565
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9811.24it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.13/bin.13.faa
Total: 641, Completed: 41, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 26
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8033.53it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.12/bin.12.faa
Total: 641, Completed: 42, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.28/bin.28.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.28/bin.28.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.28/bin.28.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 18
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53635.60it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.28/bin.28.faa
Total: 641, Completed: 43, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.29/bin.29.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.29/bin.29.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.29/bin.29.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 631
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12509.11it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.29/bin.29.faa
Total: 641, Completed: 44, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.36/bin.36.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.36/bin.36.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.36/bin.36.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11551.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.36/bin.36.faa
Total: 641, Completed: 45, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.23/bin.23.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.23/bin.23.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.23/bin.23.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 256
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17447.19it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.23/bin.23.faa
Total: 641, Completed: 46, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56527.01it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A10/bin.17/bin.17.faa
Total: 641, Completed: 47, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 393
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 26035.41it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.5/bin.5.faa
Total: 641, Completed: 48, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8119.06it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.16/bin.16.faa
Total: 641, Completed: 49, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 107
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8429.07it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.9/bin.9.faa
Total: 641, Completed: 50, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 126
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 45889.54it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.10/bin.10.faa
Total: 641, Completed: 51, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.56/bin.56.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.56/bin.56.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.56/bin.56.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8540.63it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.56/bin.56.faa
Total: 641, Completed: 52, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.40/bin.40.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.40/bin.40.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.40/bin.40.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 242
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58497.96it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.40/bin.40.faa
Total: 641, Completed: 53, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.51/bin.51.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.51/bin.51.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.51/bin.51.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 707
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14246.96it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.51/bin.51.faa
Total: 641, Completed: 54, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.42/bin.42.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.42/bin.42.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.42/bin.42.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 279
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54050.31it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.42/bin.42.faa
Total: 641, Completed: 55, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.27/bin.27.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.27/bin.27.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.27/bin.27.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 486
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51653.99it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.27/bin.27.faa
Total: 641, Completed: 56, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 55
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17848.10it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.13/bin.13.faa
Total: 641, Completed: 57, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 6
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9932.05it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.12/bin.12.faa
Total: 641, Completed: 58, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 527
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 49344.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.2/bin.2.faa
Total: 641, Completed: 59, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.58/bin.58.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.58/bin.58.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.58/bin.58.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 5669.51it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.58/bin.58.faa
Total: 641, Completed: 60, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.28/bin.28.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.28/bin.28.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.28/bin.28.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 193
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 50963.60it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.28/bin.28.faa
Total: 641, Completed: 61, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.29/bin.29.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.29/bin.29.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.29/bin.29.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51463.85it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.29/bin.29.faa
Total: 641, Completed: 62, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.49/bin.49.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.49/bin.49.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.49/bin.49.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 96
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12203.39it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.49/bin.49.faa
Total: 641, Completed: 63, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.23/bin.23.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.23/bin.23.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.23/bin.23.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 734
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10467.44it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.23/bin.23.faa
Total: 641, Completed: 64, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 7
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 23392.66it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D2/bin.6/bin.6.faa
Total: 641, Completed: 65, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0.001s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1637
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.003s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 28591.03it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.8/bin.8.faa
Total: 641, Completed: 66, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 531
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13499.53it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.16/bin.16.faa
Total: 641, Completed: 67, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.27/bin.27.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.27/bin.27.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.27/bin.27.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15218.81it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.27/bin.27.faa
Total: 641, Completed: 68, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 159
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56603.29it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.13/bin.13.faa
Total: 641, Completed: 69, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21664.79it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.12/bin.12.faa
Total: 641, Completed: 70, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.28/bin.28.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.28/bin.28.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.28/bin.28.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 23
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 47771.12it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.28/bin.28.faa
Total: 641, Completed: 71, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.31/bin.31.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.31/bin.31.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.31/bin.31.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 603
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21421.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.31/bin.31.faa
Total: 641, Completed: 72, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53498.78it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.20/bin.20.faa
Total: 641, Completed: 73, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 701
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10683.40it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G2/bin.24/bin.24.faa
Total: 641, Completed: 74, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A2/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A2/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A2/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 631
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7630.17it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A2/bin.1/bin.1.faa
Total: 641, Completed: 75, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 184
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17749.91it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.5/bin.5.faa
Total: 641, Completed: 76, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 391
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 35305.59it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.4/bin.4.faa
Total: 641, Completed: 77, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 24528.09it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.18/bin.18.faa
Total: 641, Completed: 78, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 391
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14593.96it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.1/bin.1.faa
Total: 641, Completed: 79, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.27/bin.27.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.27/bin.27.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.27/bin.27.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1393
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 26990.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.27/bin.27.faa
Total: 641, Completed: 80, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9633.22it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.19/bin.19.faa
Total: 641, Completed: 81, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 10
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 47662.55it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.12/bin.12.faa
Total: 641, Completed: 82, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.28/bin.28.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.28/bin.28.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.28/bin.28.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 272
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9562.94it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.28/bin.28.faa
Total: 641, Completed: 83, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.21/bin.21.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.21/bin.21.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.21/bin.21.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 631
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 29516.57it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.21/bin.21.faa
Total: 641, Completed: 84, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.23/bin.23.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.23/bin.23.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.23/bin.23.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 23
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13693.45it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.23/bin.23.faa
Total: 641, Completed: 85, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 43374.40it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A8/bin.24/bin.24.faa
Total: 641, Completed: 86, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 177
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10899.96it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.15/bin.15.faa
Total: 641, Completed: 87, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 18741.30it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.4/bin.4.faa
Total: 641, Completed: 88, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 271
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 46916.15it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.9/bin.9.faa
Total: 641, Completed: 89, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 243
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52298.05it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.10/bin.10.faa
Total: 641, Completed: 90, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 52
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17317.52it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.26/bin.26.faa
Total: 641, Completed: 91, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.27/bin.27.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.27/bin.27.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.27/bin.27.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51150.05it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.27/bin.27.faa
Total: 641, Completed: 92, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 631
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8826.40it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.25/bin.25.faa
Total: 641, Completed: 93, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 644
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 42842.74it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D1/bin.11/bin.11.faa
Total: 641, Completed: 94, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E10/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E10/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E10/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 295
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9541.18it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E10/bin.9/bin.9.faa
Total: 641, Completed: 95, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E10/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E10/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E10/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 531
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56603.29it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E10/bin.12/bin.12.faa
Total: 641, Completed: 96, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E10/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E10/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E10/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 548
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 18825.42it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E10/bin.2/bin.2.faa
Total: 641, Completed: 97, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 50
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56679.78it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.16/bin.16.faa
Total: 641, Completed: 98, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16200.48it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.10/bin.10.faa
Total: 641, Completed: 99, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 528
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11912.25it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.2/bin.2.faa
Total: 641, Completed: 100, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 602
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13657.78it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.20/bin.20.faa
Total: 641, Completed: 101, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 532
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56299.38it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F8/bin.17/bin.17.faa
Total: 641, Completed: 102, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 155
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10250.01it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.16/bin.16.faa
Total: 641, Completed: 103, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 293
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 22957.33it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.10/bin.10.faa
Total: 641, Completed: 104, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 362
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58335.24it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.22/bin.22.faa
Total: 641, Completed: 105, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 93
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12893.65it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.26/bin.26.faa
Total: 641, Completed: 106, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 618
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51275.11it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.19/bin.19.faa
Total: 641, Completed: 107, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.21/bin.21.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.21/bin.21.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.21/bin.21.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 100
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54260.08it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.21/bin.21.faa
Total: 641, Completed: 108, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.36/bin.36.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.36/bin.36.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.36/bin.36.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57065.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.36/bin.36.faa
Total: 641, Completed: 109, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.31/bin.31.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.31/bin.31.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.31/bin.31.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 75
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16448.25it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D5/bin.31/bin.31.faa
Total: 641, Completed: 110, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 110
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53362.65it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.5/bin.5.faa
Total: 641, Completed: 111, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 643
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 60176.53it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.16/bin.16.faa
Total: 641, Completed: 112, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 50840.05it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.4/bin.4.faa
Total: 641, Completed: 113, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 105
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17690.02it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.10/bin.10.faa
Total: 641, Completed: 114, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 600
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15397.59it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.1/bin.1.faa
Total: 641, Completed: 115, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 69
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12554.04it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.19/bin.19.faa
Total: 641, Completed: 116, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 29
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57143.11it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.12/bin.12.faa
Total: 641, Completed: 117, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19266.44it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.20/bin.20.faa
Total: 641, Completed: 118, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55406.92it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A1/bin.17/bin.17.faa
Total: 641, Completed: 119, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 378
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20145.55it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.8/bin.8.faa
Total: 641, Completed: 120, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 752
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57299.23it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.4/bin.4.faa
Total: 641, Completed: 121, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 184
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13697.92it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.9/bin.9.faa
Total: 641, Completed: 122, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 295
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53159.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.10/bin.10.faa
Total: 641, Completed: 123, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 292
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 59409.41it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F3/bin.2/bin.2.faa
Total: 641, Completed: 124, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E9/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E9/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E9/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 295
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54684.54it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E9/bin.3/bin.3.faa
Total: 641, Completed: 125, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E9/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E9/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E9/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 488
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10202.64it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E9/bin.11/bin.11.faa
Total: 641, Completed: 126, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E9/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E9/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E9/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1572
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 59409.41it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E9/bin.6/bin.6.faa
Total: 641, Completed: 127, Failed: 0
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A1/bin.3/._bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/._bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A1/bin.3/._bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/._bin.3.align'
Error: Error detecting input file format. First line must begin with '>' (FASTA) or '@' (FASTQ).
Traceback (most recent call last):
  File "/home/ubuntu/venv3/bin/deeparg", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/venv3/lib/python3.12/site-packages/deeparg/entry.py", line 358, in main
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/venv3/lib/python3.12/site-packages/deeparg/entry.py", line 214, in predict
    _run_command(cmd)
  File "/home/ubuntu/venv3/lib/python3.12/site-packages/deeparg/entry.py", line 24, in _run_command
    subprocess.run(command, check=True)
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'blastp', '-q', '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A1/bin.3/._bin.3.faa', '-d', '/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features', '-k', '1000', '--id', '50', '--sensitive', '-e', '1e-10', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/._bin.3.align']' returned non-zero exit status 1.

FAILED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A1/bin.3/._bin.3.faa
Total: 641, Completed: 127, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A1/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A1/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A1/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 810
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 46345.90it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A1/bin.3/bin.3.faa
Total: 641, Completed: 128, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20671.78it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.16/bin.16.faa
Total: 641, Completed: 129, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 717
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 22453.45it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.4/bin.4.faa
Total: 641, Completed: 130, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9362.29it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.22/bin.22.faa
Total: 641, Completed: 131, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.30/bin.30.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.30/bin.30.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.30/bin.30.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 9
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 6886.07it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.30/bin.30.faa
Total: 641, Completed: 132, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 689
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14979.66it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.20/bin.20.faa
Total: 641, Completed: 133, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 159
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 6632.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F11/bin.17/bin.17.faa
Total: 641, Completed: 134, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54542.31it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.7/bin.7.faa
Total: 641, Completed: 135, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 159
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10126.28it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.9/bin.9.faa
Total: 641, Completed: 136, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 601
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 27449.63it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.10/bin.10.faa
Total: 641, Completed: 137, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20311.40it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.18/bin.18.faa
Total: 641, Completed: 138, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57852.47it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G4/bin.13/bin.13.faa
Total: 641, Completed: 139, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 278
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10200.16it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.9/bin.9.faa
Total: 641, Completed: 140, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 545
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 23083.68it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.1/bin.1.faa
Total: 641, Completed: 141, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 567
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15511.48it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.19/bin.19.faa
Total: 641, Completed: 142, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 6062.01it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.12/bin.12.faa
Total: 641, Completed: 143, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 292
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54400.83it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.6/bin.6.faa
Total: 641, Completed: 144, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 28767.52it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F6/bin.14/bin.14.faa
Total: 641, Completed: 145, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55260.92it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.5/bin.5.faa
Total: 641, Completed: 146, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 193
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11187.79it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.9/bin.9.faa
Total: 641, Completed: 147, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 176
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16730.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.12/bin.12.faa
Total: 641, Completed: 148, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 23
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58661.59it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.2/bin.2.faa
Total: 641, Completed: 149, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.21/bin.21.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.21/bin.21.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.21/bin.21.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 631
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 50594.74it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.21/bin.21.faa
Total: 641, Completed: 150, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 531
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53980.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E6/bin.14/bin.14.faa
Total: 641, Completed: 151, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 468
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19831.22it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.5/bin.5.faa
Total: 641, Completed: 152, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 176
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10230.01it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.16/bin.16.faa
Total: 641, Completed: 153, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 637
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21183.35it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.10/bin.10.faa
Total: 641, Completed: 154, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 718
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 47180.02it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.26/bin.26.faa
Total: 641, Completed: 155, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.27/bin.27.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.27/bin.27.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.27/bin.27.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 194
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14344.40it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.27/bin.27.faa
Total: 641, Completed: 156, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 632
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11702.86it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.13/bin.13.faa
Total: 641, Completed: 157, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.28/bin.28.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.28/bin.28.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.28/bin.28.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20049.25it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.28/bin.28.faa
Total: 641, Completed: 158, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.21/bin.21.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.21/bin.21.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.21/bin.21.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 241
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56987.83it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.21/bin.21.faa
Total: 641, Completed: 159, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 39
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 25297.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.20/bin.20.faa
Total: 641, Completed: 160, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 49
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 22489.57it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D8/bin.17/bin.17.faa
Total: 641, Completed: 161, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 127
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16584.83it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.8/bin.8.faa
Total: 641, Completed: 162, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 717
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20815.40it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.16/bin.16.faa
Total: 641, Completed: 163, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 47662.55it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.15/bin.15.faa
Total: 641, Completed: 164, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 247
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16435.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.25/bin.25.faa
Total: 641, Completed: 165, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 18363.85it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E8/bin.14/bin.14.faa
Total: 641, Completed: 166, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B2/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B2/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B2/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 105
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51212.50it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B2/bin.11/bin.11.faa
Total: 641, Completed: 167, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 798
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10389.66it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.5/bin.5.faa
Total: 641, Completed: 168, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.38/bin.38.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.38/bin.38.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.38/bin.38.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 435
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 29289.83it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.38/bin.38.faa
Total: 641, Completed: 169, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 93
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16094.80it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.16/bin.16.faa
Total: 641, Completed: 170, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 27306.67it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.22/bin.22.faa
Total: 641, Completed: 171, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.62/bin.62.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.62

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.62/bin.62.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.62.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.62/bin.62.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.62 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.62.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.62.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.62.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.62.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 47608.44it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.62/bin.62.faa
Total: 641, Completed: 172, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.33/bin.33.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.33/bin.33.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.33/bin.33.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57221.06it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.33/bin.33.faa
Total: 641, Completed: 173, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.57/bin.57.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.57

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.57/bin.57.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.57.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.57/bin.57.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.57 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.57.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.57.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.57.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.57.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20550.24it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.57/bin.57.faa
Total: 641, Completed: 174, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7423.55it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.26/bin.26.faa
Total: 641, Completed: 175, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.45/bin.45.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.45/bin.45.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.45/bin.45.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 105
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12737.03it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.45/bin.45.faa
Total: 641, Completed: 176, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.52/bin.52.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.52/bin.52.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.52/bin.52.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17870.92it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.52/bin.52.faa
Total: 641, Completed: 177, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.27/bin.27.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.27/bin.27.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.27/bin.27.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 129
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53092.46it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.27/bin.27.faa
Total: 641, Completed: 178, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.54/bin.54.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.54/bin.54.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.54/bin.54.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51463.85it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.54/bin.54.faa
Total: 641, Completed: 179, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 597
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16200.48it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.13/bin.13.faa
Total: 641, Completed: 180, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.43/bin.43.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.43/bin.43.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.43/bin.43.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 64
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53980.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.43/bin.43.faa
Total: 641, Completed: 181, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.48/bin.48.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.48/bin.48.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.48/bin.48.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 79
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13306.80it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.48/bin.48.faa
Total: 641, Completed: 182, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.47/bin.47.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.47/bin.47.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.47/bin.47.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 51
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17246.32it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.47/bin.47.faa
Total: 641, Completed: 183, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 27377.96it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.25/bin.25.faa
Total: 641, Completed: 184, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.29/bin.29.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.29/bin.29.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.29/bin.29.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52891.60it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.29/bin.29.faa
Total: 641, Completed: 185, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.49/bin.49.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.49/bin.49.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.49/bin.49.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17454.45it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.49/bin.49.faa
Total: 641, Completed: 186, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10148.33it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.6/bin.6.faa
Total: 641, Completed: 187, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19719.34it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.24/bin.24.faa
Total: 641, Completed: 188, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.55/bin.55.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.55/bin.55.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.55/bin.55.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 202
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19803.14it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D6/bin.55/bin.55.faa
Total: 641, Completed: 189, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14706.54it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.7/bin.7.faa
Total: 641, Completed: 190, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 6502.80it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.15/bin.15.faa
Total: 641, Completed: 191, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 744
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8338.58it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.3/bin.3.faa
Total: 641, Completed: 192, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.21/bin.21.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.21/bin.21.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.21/bin.21.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 25
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55333.83it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.21/bin.21.faa
Total: 641, Completed: 193, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 6
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 23121.85it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.25/bin.25.faa
Total: 641, Completed: 194, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.29/bin.29.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.29/bin.29.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.29/bin.29.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 632
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20001.45it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.29/bin.29.faa
Total: 641, Completed: 195, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 247
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 49171.21it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E5/bin.6/bin.6.faa
Total: 641, Completed: 196, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 21
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11422.40it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.8/bin.8.faa
Total: 641, Completed: 197, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.41/bin.41.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.41/bin.41.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.41/bin.41.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14227.63it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.41/bin.41.faa
Total: 641, Completed: 198, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 192
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 18526.08it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.4/bin.4.faa
Total: 641, Completed: 199, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 29558.17it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.9/bin.9.faa
Total: 641, Completed: 200, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 379
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10285.20it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.1/bin.1.faa
Total: 641, Completed: 201, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 27
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16851.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.26/bin.26.faa
Total: 641, Completed: 202, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.70/bin.70.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.70

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.70/bin.70.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.70.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.70/bin.70.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.70 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.70.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.70.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.70.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.70.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 41080.35it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.70/bin.70.faa
Total: 641, Completed: 203, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.27/bin.27.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.27/bin.27.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.27/bin.27.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 114
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8019.70it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.27/bin.27.faa
Total: 641, Completed: 204, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.44/bin.44.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.44/bin.44.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.44/bin.44.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 106
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17534.72it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.44/bin.44.faa
Total: 641, Completed: 205, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1226
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9873.60it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.12/bin.12.faa
Total: 641, Completed: 206, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.43/bin.43.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.43/bin.43.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.43/bin.43.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.43.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 564
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12073.41it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.43/bin.43.faa
Total: 641, Completed: 207, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.58/bin.58.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.58/bin.58.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.58/bin.58.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.58.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 406
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56679.78it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.58/bin.58.faa
Total: 641, Completed: 208, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.48/bin.48.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.48/bin.48.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.48/bin.48.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 5
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16837.83it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.48/bin.48.faa
Total: 641, Completed: 209, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.71/bin.71.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.71

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.71/bin.71.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.71.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.71/bin.71.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.71 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.71.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.71.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.71.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.71.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 179
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54899.27it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.71/bin.71.faa
Total: 641, Completed: 210, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.61/bin.61.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.61/bin.61.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.61/bin.61.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 712
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51717.68it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.61/bin.61.faa
Total: 641, Completed: 211, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 617
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20805.08it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.11/bin.11.faa
Total: 641, Completed: 212, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.31/bin.31.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.31/bin.31.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.31/bin.31.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 527
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55924.05it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.31/bin.31.faa
Total: 641, Completed: 213, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 32
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15941.86it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.14/bin.14.faa
Total: 641, Completed: 214, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.59/bin.59.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.59

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.59/bin.59.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.59.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.59/bin.59.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.59 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.59.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.59.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.59.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.59.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 23
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54260.08it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.59/bin.59.faa
Total: 641, Completed: 215, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 645
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54400.83it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C7/bin.17/bin.17.faa
Total: 641, Completed: 216, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10543.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.5/bin.5.faa
Total: 641, Completed: 217, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 232
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56833.39it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.7/bin.7.faa
Total: 641, Completed: 218, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 583
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 49171.21it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.9/bin.9.faa
Total: 641, Completed: 219, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 99
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 50051.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.10/bin.10.faa
Total: 641, Completed: 220, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 166
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8393.64it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.22/bin.22.faa
Total: 641, Completed: 221, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 83
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16027.15it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.26/bin.26.faa
Total: 641, Completed: 222, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 299
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14985.01it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.19/bin.19.faa
Total: 641, Completed: 223, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.32/bin.32.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.32

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.32/bin.32.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.32.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.32/bin.32.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.32 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.32.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.32.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.32.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.32.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 523
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21879.52it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.32/bin.32.faa
Total: 641, Completed: 224, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 38836.15it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.6/bin.6.faa
Total: 641, Completed: 225, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 31
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16519.51it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.24/bin.24.faa
Total: 641, Completed: 226, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 115
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7927.24it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G11/bin.17/bin.17.faa
Total: 641, Completed: 227, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B8/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B8/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B8/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51717.68it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B8/bin.8/bin.8.faa
Total: 641, Completed: 228, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B8/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B8/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B8/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 468
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21631.27it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B8/bin.15/bin.15.faa
Total: 641, Completed: 229, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B8/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B8/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B8/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 5
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52758.54it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B8/bin.12/bin.12.faa
Total: 641, Completed: 230, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 180
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 44057.82it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.7/bin.7.faa
Total: 641, Completed: 231, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.37/bin.37.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.37/bin.37.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.37/bin.37.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 24528.09it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.37/bin.37.faa
Total: 641, Completed: 232, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 236
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 6779.22it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.9/bin.9.faa
Total: 641, Completed: 233, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51275.11it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.18/bin.18.faa
Total: 641, Completed: 234, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 310
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52626.15it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.1/bin.1.faa
Total: 641, Completed: 235, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.33/bin.33.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.33/bin.33.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.33/bin.33.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10369.11it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.33/bin.33.faa
Total: 641, Completed: 236, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 42
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 29392.46it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.26/bin.26.faa
Total: 641, Completed: 237, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 83
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53092.46it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.19/bin.19.faa
Total: 641, Completed: 238, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.21/bin.21.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.21/bin.21.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.21/bin.21.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 80
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8461.38it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.21/bin.21.faa
Total: 641, Completed: 239, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 99
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 50533.78it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.25/bin.25.faa
Total: 641, Completed: 240, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 523
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54189.97it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G10/bin.24/bin.24.faa
Total: 641, Completed: 241, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 21
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 18355.82it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.5/bin.5.faa
Total: 641, Completed: 242, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10168.01it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.7/bin.7.faa
Total: 641, Completed: 243, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 36
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15263.11it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.10/bin.10.faa
Total: 641, Completed: 244, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 413
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12818.78it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C5/bin.22/bin.22.faa
Total: 641, Completed: 245, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 12
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14747.90it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.9/bin.9.faa
Total: 641, Completed: 246, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 643
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54684.54it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.10/bin.10.faa
Total: 641, Completed: 247, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 40
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55115.69it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.13/bin.13.faa
Total: 641, Completed: 248, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 24
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19934.90it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.11/bin.11.faa
Total: 641, Completed: 249, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 44
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 18575.31it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.24/bin.24.faa
Total: 641, Completed: 250, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 83
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21531.33it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.14/bin.14.faa
Total: 641, Completed: 251, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 26
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53430.62it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C6/bin.17/bin.17.faa
Total: 641, Completed: 252, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 527
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8245.14it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.7/bin.7.faa
Total: 641, Completed: 253, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 55
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16539.05it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.16/bin.16.faa
Total: 641, Completed: 254, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 285
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55043.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.4/bin.4.faa
Total: 641, Completed: 255, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 107
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11244.78it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.18/bin.18.faa
Total: 641, Completed: 256, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 8
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14169.95it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.1/bin.1.faa
Total: 641, Completed: 257, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.40/bin.40.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.40/bin.40.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.40/bin.40.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 43645.20it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.40/bin.40.faa
Total: 641, Completed: 258, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.30/bin.30.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.30/bin.30.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.30/bin.30.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 301
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13879.23it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.30/bin.30.faa
Total: 641, Completed: 259, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.42/bin.42.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.42/bin.42.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.42/bin.42.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7878.11it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.42/bin.42.faa
Total: 641, Completed: 260, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.21/bin.21.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.21/bin.21.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.21/bin.21.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 802
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8640.92it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.21/bin.21.faa
Total: 641, Completed: 261, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.36/bin.36.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.36/bin.36.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.36/bin.36.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 126
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 23392.66it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.36/bin.36.faa
Total: 641, Completed: 262, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.31/bin.31.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.31/bin.31.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.31/bin.31.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 617
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52692.26it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D11/bin.31/bin.31.faa
Total: 641, Completed: 263, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E3/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E3/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E3/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 271
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14847.09it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E3/bin.22/bin.22.faa
Total: 641, Completed: 264, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E3/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E3/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E3/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 238
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15598.01it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E3/bin.20/bin.20.faa
Total: 641, Completed: 265, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E3/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E3/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E3/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13774.40it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E3/bin.14/bin.14.faa
Total: 641, Completed: 266, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H8/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H8/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H8/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 167
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12546.53it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H8/bin.13/bin.13.faa
Total: 641, Completed: 267, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 235
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53842.16it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.8/bin.8.faa
Total: 641, Completed: 268, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 94
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8417.23it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.7/bin.7.faa
Total: 641, Completed: 269, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 115
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57065.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.15/bin.15.faa
Total: 641, Completed: 270, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 356
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8112.77it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.10/bin.10.faa
Total: 641, Completed: 271, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 523
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21498.23it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G12/bin.1/bin.1.faa
Total: 641, Completed: 272, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17690.02it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.5/bin.5.faa
Total: 641, Completed: 273, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 689
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10462.22it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.8/bin.8.faa
Total: 641, Completed: 274, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9783.77it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.9/bin.9.faa
Total: 641, Completed: 275, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12606.87it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.1/bin.1.faa
Total: 641, Completed: 276, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 643
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 22227.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.19/bin.19.faa
Total: 641, Completed: 277, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 292
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53498.78it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.13/bin.13.faa
Total: 641, Completed: 278, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15465.72it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.12/bin.12.faa
Total: 641, Completed: 279, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 29
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7241.55it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.3/bin.3.faa
Total: 641, Completed: 280, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 622
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 44906.90it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.11/bin.11.faa
Total: 641, Completed: 281, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16710.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S2A2/bin.14/bin.14.faa
Total: 641, Completed: 282, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 6688.41it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.15/bin.15.faa
Total: 641, Completed: 283, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15448.63it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.26/bin.26.faa
Total: 641, Completed: 284, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10621.18it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.19/bin.19.faa
Total: 641, Completed: 285, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 292
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 25716.15it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.11/bin.11.faa
Total: 641, Completed: 286, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11409.97it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.6/bin.6.faa
Total: 641, Completed: 287, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 149
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55775.32it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G1/bin.17/bin.17.faa
Total: 641, Completed: 288, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 99
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11725.76it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.7/bin.7.faa
Total: 641, Completed: 289, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 540
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 34836.41it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.10/bin.10.faa
Total: 641, Completed: 290, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 773
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7969.42it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.18/bin.18.faa
Total: 641, Completed: 291, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 159
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12260.46it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.13/bin.13.faa
Total: 641, Completed: 292, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1067
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57221.06it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G6/bin.14/bin.14.faa
Total: 641, Completed: 293, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.37/bin.37.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.37/bin.37.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.37/bin.37.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 527
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54684.54it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.37/bin.37.faa
Total: 641, Completed: 294, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 37
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 27906.21it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.16/bin.16.faa
Total: 641, Completed: 295, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 8
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17795.10it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.15/bin.15.faa
Total: 641, Completed: 296, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.44/bin.44.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.44/bin.44.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.44/bin.44.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 641
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14398.57it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.44/bin.44.faa
Total: 641, Completed: 297, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 108
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 61320.23it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.12/bin.12.faa
Total: 641, Completed: 298, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.28/bin.28.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.28/bin.28.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.28/bin.28.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 26
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8193.60it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.28/bin.28.faa
Total: 641, Completed: 299, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 392
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 24614.46it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.3/bin.3.faa
Total: 641, Completed: 300, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57614.07it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.25/bin.25.faa
Total: 641, Completed: 301, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.29/bin.29.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.29/bin.29.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.29/bin.29.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 285
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9861.99it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.29/bin.29.faa
Total: 641, Completed: 302, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10837.99it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.11/bin.11.faa
Total: 641, Completed: 303, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 617
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19508.39it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.20/bin.20.faa
Total: 641, Completed: 304, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 21
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17382.11it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D12/bin.14/bin.14.faa
Total: 641, Completed: 305, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H1/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H1/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H1/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 532
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56910.50it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H1/bin.4/bin.4.faa
Total: 641, Completed: 306, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H1/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H1/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H1/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 72
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51527.08it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H1/bin.2/bin.2.faa
Total: 641, Completed: 307, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H1/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H1/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H1/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 58
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10012.66it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H1/bin.3/bin.3.faa
Total: 641, Completed: 308, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 24
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53635.60it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.9/bin.9.faa
Total: 641, Completed: 309, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 29392.46it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.22/bin.22.faa
Total: 641, Completed: 310, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 283
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12858.07it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.26/bin.26.faa
Total: 641, Completed: 311, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 287
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11217.72it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.19/bin.19.faa
Total: 641, Completed: 312, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55188.21it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.12/bin.12.faa
Total: 641, Completed: 313, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 179
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 24413.88it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.25/bin.25.faa
Total: 641, Completed: 314, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.23/bin.23.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.23/bin.23.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.23/bin.23.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 81
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13340.66it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H4/bin.23/bin.23.faa
Total: 641, Completed: 315, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A5/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A5/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A5/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 58
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13711.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A5/bin.6/bin.6.faa
Total: 641, Completed: 316, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E1/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E1/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E1/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 6634.46it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E1/bin.6/bin.6.faa
Total: 641, Completed: 317, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E1/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E1/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E1/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 268
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11190.78it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E1/bin.14/bin.14.faa
Total: 641, Completed: 318, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C1/bin.41/bin.41.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C1/bin.41/bin.41.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C1/bin.41/bin.41.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 6181.73it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C1/bin.41/bin.41.faa
Total: 641, Completed: 319, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C1/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C1/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C1/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14046.56it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C1/bin.22/bin.22.faa
Total: 641, Completed: 320, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C1/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C1/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C1/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 12
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53567.10it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C1/bin.19/bin.19.faa
Total: 641, Completed: 321, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 23
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 59662.93it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.5/bin.5.faa
Total: 641, Completed: 322, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19436.07it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.16/bin.16.faa
Total: 641, Completed: 323, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58012.50it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.9/bin.9.faa
Total: 641, Completed: 324, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 27
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12224.73it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B10/bin.11/bin.11.faa
Total: 641, Completed: 325, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 126
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56910.50it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.4/bin.4.faa
Total: 641, Completed: 326, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14285.78it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.18/bin.18.faa
Total: 641, Completed: 327, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 43419.30it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.22/bin.22.faa
Total: 641, Completed: 328, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.42/bin.42.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.42/bin.42.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.42/bin.42.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 23
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 59241.58it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.42/bin.42.faa
Total: 641, Completed: 329, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 557
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52428.80it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.19/bin.19.faa
Total: 641, Completed: 330, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 256
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9078.58it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.13/bin.13.faa
Total: 641, Completed: 331, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 631
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9545.53it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.12/bin.12.faa
Total: 641, Completed: 332, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.28/bin.28.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.28/bin.28.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.28/bin.28.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 7
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52038.51it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.28/bin.28.faa
Total: 641, Completed: 333, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.29/bin.29.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.29/bin.29.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.29/bin.29.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 38
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57535.03it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.29/bin.29.faa
Total: 641, Completed: 334, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.34/bin.34.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.34/bin.34.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.34/bin.34.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 165
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 18918.83it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.34/bin.34.faa
Total: 641, Completed: 335, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 247
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58335.24it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D7/bin.17/bin.17.faa
Total: 641, Completed: 336, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.46/bin.46.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.46/bin.46.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.46/bin.46.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 20
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51974.03it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.46/bin.46.faa
Total: 641, Completed: 337, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58826.14it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.8/bin.8.faa
Total: 641, Completed: 338, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 191
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57299.23it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.7/bin.7.faa
Total: 641, Completed: 339, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 105
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 6008.17it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.10/bin.10.faa
Total: 641, Completed: 340, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 600
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12383.54it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.22/bin.22.faa
Total: 641, Completed: 341, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 643
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55406.92it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.19/bin.19.faa
Total: 641, Completed: 342, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 600
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20753.61it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.13/bin.13.faa
Total: 641, Completed: 343, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 5
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 26800.66it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.2/bin.2.faa
Total: 641, Completed: 344, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.28/bin.28.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.28/bin.28.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.28/bin.28.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 110
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 49344.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.28/bin.28.faa
Total: 641, Completed: 345, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 59747.92it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.3/bin.3.faa
Total: 641, Completed: 346, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8612.53it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.11/bin.11.faa
Total: 641, Completed: 347, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.23/bin.23.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.23/bin.23.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.23/bin.23.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 465
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21698.42it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.23/bin.23.faa
Total: 641, Completed: 348, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 292
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8053.58it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.20/bin.20.faa
Total: 641, Completed: 349, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.35/bin.35.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.35/bin.35.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.35/bin.35.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 71
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15044.13it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.35/bin.35.faa
Total: 641, Completed: 350, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 48265.87it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.14/bin.14.faa
Total: 641, Completed: 351, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.39/bin.39.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.39/bin.39.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.39/bin.39.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 119
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15125.51it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H11/bin.39/bin.39.faa
Total: 641, Completed: 352, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 83
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10250.01it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.8/bin.8.faa
Total: 641, Completed: 353, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 193
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11844.97it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.16/bin.16.faa
Total: 641, Completed: 354, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 559
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7108.99it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.4/bin.4.faa
Total: 641, Completed: 355, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 677
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16200.48it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.9/bin.9.faa
Total: 641, Completed: 356, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1089
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16730.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.10/bin.10.faa
Total: 641, Completed: 357, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.27/bin.27.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.27/bin.27.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.27/bin.27.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12698.47it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.27/bin.27.faa
Total: 641, Completed: 358, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 204
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17091.70it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.13/bin.13.faa
Total: 641, Completed: 359, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 98
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7876.63it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.3/bin.3.faa
Total: 641, Completed: 360, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 81
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11715.93it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.24/bin.24.faa
Total: 641, Completed: 361, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 248
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 22708.74it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F9/bin.14/bin.14.faa
Total: 641, Completed: 362, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9242.63it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.15/bin.15.faa
Total: 641, Completed: 363, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 262
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11529.15it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.25/bin.25.faa
Total: 641, Completed: 364, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 416
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12182.12it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.6/bin.6.faa
Total: 641, Completed: 365, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17029.25it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H3/bin.14/bin.14.faa
Total: 641, Completed: 366, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G9/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G9/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G9/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 63
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19160.82it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G9/bin.7/bin.7.faa
Total: 641, Completed: 367, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G9/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G9/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G9/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 99
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20661.60it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G9/bin.3/bin.3.faa
Total: 641, Completed: 368, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 96
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19463.13it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.8/bin.8.faa
Total: 641, Completed: 369, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 23
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15120.06it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.15/bin.15.faa
Total: 641, Completed: 370, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 9
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58908.76it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.4/bin.4.faa
Total: 641, Completed: 371, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 616
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7829.58it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.22/bin.22.faa
Total: 641, Completed: 372, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 752
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15114.61it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.13/bin.13.faa
Total: 641, Completed: 373, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 271
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 26149.03it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.6/bin.6.faa
Total: 641, Completed: 374, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21045.18it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B11/bin.14/bin.14.faa
Total: 641, Completed: 375, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 567
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53159.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.19/bin.19.faa
Total: 641, Completed: 376, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54899.27it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.12/bin.12.faa
Total: 641, Completed: 377, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 6
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 32742.42it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.2/bin.2.faa
Total: 641, Completed: 378, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.29/bin.29.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.29/bin.29.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.29/bin.29.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 166
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56299.38it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.29/bin.29.faa
Total: 641, Completed: 379, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.31/bin.31.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.31/bin.31.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.31/bin.31.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7641.29it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.31/bin.31.faa
Total: 641, Completed: 380, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 98
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9324.82it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F12/bin.14/bin.14.faa
Total: 641, Completed: 381, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A6/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A6/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A6/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 482
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8504.27it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A6/bin.5/bin.5.faa
Total: 641, Completed: 382, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A6/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A6/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A6/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 71
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58991.62it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A6/bin.10/bin.10.faa
Total: 641, Completed: 383, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A6/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A6/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A6/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14963.62it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A6/bin.14/bin.14.faa
Total: 641, Completed: 384, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9988.82it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.16/bin.16.faa
Total: 641, Completed: 385, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 159
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17317.52it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.4/bin.4.faa
Total: 641, Completed: 386, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 59074.70it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.10/bin.10.faa
Total: 641, Completed: 387, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1113
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13206.25it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.13/bin.13.faa
Total: 641, Completed: 388, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20440.08it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.12/bin.12.faa
Total: 641, Completed: 389, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 5
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 59662.93it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.2/bin.2.faa
Total: 641, Completed: 390, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 535
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 18236.10it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.11/bin.11.faa
Total: 641, Completed: 391, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 292
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10948.33it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G3/bin.24/bin.24.faa
Total: 641, Completed: 392, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9882.90it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.7/bin.7.faa
Total: 641, Completed: 393, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.38/bin.38.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.38/bin.38.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.38/bin.38.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8303.91it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.38/bin.38.faa
Total: 641, Completed: 394, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 436
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56148.65it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.16/bin.16.faa
Total: 641, Completed: 395, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 56
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.004s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9014.19it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.9/bin.9.faa
Total: 641, Completed: 396, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51025.60it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.18/bin.18.faa
Total: 641, Completed: 397, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.56/bin.56.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.56/bin.56.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.56/bin.56.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.56.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 254
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57221.06it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.56/bin.56.faa
Total: 641, Completed: 398, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13050.11it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.22/bin.22.faa
Total: 641, Completed: 399, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10629.25it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.1/bin.1.faa
Total: 641, Completed: 400, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51590.46it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.26/bin.26.faa
Total: 641, Completed: 401, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.27/bin.27.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.27/bin.27.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.27/bin.27.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.27.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13078.59it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.27/bin.27.faa
Total: 641, Completed: 402, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 105
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9628.80it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.13/bin.13.faa
Total: 641, Completed: 403, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 257
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53227.21it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.12/bin.12.faa
Total: 641, Completed: 404, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 40721.40it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.25/bin.25.faa
Total: 641, Completed: 405, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.23/bin.23.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.23/bin.23.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.23/bin.23.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 77
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 59833.15it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.23/bin.23.faa
Total: 641, Completed: 406, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 105
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58579.66it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.20/bin.20.faa
Total: 641, Completed: 407, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.35/bin.35.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.35/bin.35.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.35/bin.35.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 129
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21879.52it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.35/bin.35.faa
Total: 641, Completed: 408, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19544.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.14/bin.14.faa
Total: 641, Completed: 409, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.39/bin.39.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.39/bin.39.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.39/bin.39.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 53
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9727.05it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D3/bin.39/bin.39.faa
Total: 641, Completed: 410, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B7/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B7/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B7/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 22501.63it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B7/bin.4/bin.4.faa
Total: 641, Completed: 411, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B7/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B7/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B7/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 292
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14208.35it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B7/bin.2/bin.2.faa
Total: 641, Completed: 412, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 108
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58012.50it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.18/bin.18.faa
Total: 641, Completed: 413, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.51/bin.51.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.51/bin.51.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.51/bin.51.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 280
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 28378.24it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.51/bin.51.faa
Total: 641, Completed: 414, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.30/bin.30.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.30/bin.30.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.30/bin.30.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7166.08it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.30/bin.30.faa
Total: 641, Completed: 415, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 192
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55998.72it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.26/bin.26.faa
Total: 641, Completed: 416, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.47/bin.47.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.47/bin.47.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.47/bin.47.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.47.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 301
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19728.62it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.47/bin.47.faa
Total: 641, Completed: 417, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 631
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52167.96it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.25/bin.25.faa
Total: 641, Completed: 418, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.49/bin.49.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.49/bin.49.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.49/bin.49.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.49.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 527
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11178.85it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.49/bin.49.faa
Total: 641, Completed: 419, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.23/bin.23.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.23/bin.23.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.23/bin.23.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 210
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 41486.69it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.23/bin.23.faa
Total: 641, Completed: 420, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.35/bin.35.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.35/bin.35.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.35/bin.35.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.35.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 617
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14675.66it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.35/bin.35.faa
Total: 641, Completed: 421, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 365
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58012.50it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.24/bin.24.faa
Total: 641, Completed: 422, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.55/bin.55.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.55/bin.55.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.55/bin.55.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 127
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17267.62it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D9/bin.55/bin.55.faa
Total: 641, Completed: 423, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.46/bin.46.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.46/bin.46.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.46/bin.46.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 529
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21269.29it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.46/bin.46.faa
Total: 641, Completed: 424, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 798
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13600.21it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.15/bin.15.faa
Total: 641, Completed: 425, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 281
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7100.57it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.22/bin.22.faa
Total: 641, Completed: 426, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20460.02it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.1/bin.1.faa
Total: 641, Completed: 427, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.33/bin.33.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.33/bin.33.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.33/bin.33.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 71
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19599.55it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.33/bin.33.faa
Total: 641, Completed: 428, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 128
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9745.13it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.26/bin.26.faa
Total: 641, Completed: 429, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.42/bin.42.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.42/bin.42.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.42/bin.42.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.42.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51717.68it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.42/bin.42.faa
Total: 641, Completed: 430, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 75
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58497.96it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.13/bin.13.faa
Total: 641, Completed: 431, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.66/bin.66.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.66

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.66/bin.66.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.66.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.66/bin.66.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.66 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.66.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.66.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.66.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.66.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 106
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14548.40it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.66/bin.66.faa
Total: 641, Completed: 432, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 6749.77it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.3/bin.3.faa
Total: 641, Completed: 433, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.21/bin.21.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.21/bin.21.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.21/bin.21.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 93
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 59325.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.21/bin.21.faa
Total: 641, Completed: 434, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.29/bin.29.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.29/bin.29.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.29/bin.29.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.29.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12285.60it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.29/bin.29.faa
Total: 641, Completed: 435, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.31/bin.31.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.31/bin.31.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.31/bin.31.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 56
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52891.60it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.31/bin.31.faa
Total: 641, Completed: 436, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.39/bin.39.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.39/bin.39.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.39/bin.39.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 105
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 26512.67it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D10/bin.39/bin.39.faa
Total: 641, Completed: 437, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.46/bin.46.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.46/bin.46.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.46/bin.46.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 596
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9797.49it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.46/bin.46.faa
Total: 641, Completed: 438, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.41/bin.41.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.41/bin.41.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.41/bin.41.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.41.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 24921.59it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.41/bin.41.faa
Total: 641, Completed: 439, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.50/bin.50.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.50/bin.50.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.50/bin.50.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15060.34it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.50/bin.50.faa
Total: 641, Completed: 440, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 67
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55998.72it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.26/bin.26.faa
Total: 641, Completed: 441, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.61/bin.61.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.61/bin.61.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.61/bin.61.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 6
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52560.20it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.61/bin.61.faa
Total: 641, Completed: 442, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.21/bin.21.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.21/bin.21.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.21/bin.21.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 107
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 5440.08it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.21/bin.21.faa
Total: 641, Completed: 443, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 27539.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.24/bin.24.faa
Total: 641, Completed: 444, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 464
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14722.02it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C4/bin.17/bin.17.faa
Total: 641, Completed: 445, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.38/bin.38.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.38/bin.38.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.38/bin.38.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14974.31it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.38/bin.38.faa
Total: 641, Completed: 446, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.37/bin.37.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.37/bin.37.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.37/bin.37.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 6728.11it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.37/bin.37.faa
Total: 641, Completed: 447, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 13
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 29371.88it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.16/bin.16.faa
Total: 641, Completed: 448, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 138
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14624.49it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.15/bin.15.faa
Total: 641, Completed: 449, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.33/bin.33.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.33/bin.33.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.33/bin.33.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.33.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 410
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58254.22it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.33/bin.33.faa
Total: 641, Completed: 450, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.30/bin.30.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.30/bin.30.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.30/bin.30.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 223
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15785.86it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.30/bin.30.faa
Total: 641, Completed: 451, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 153
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19039.06it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.13/bin.13.faa
Total: 641, Completed: 452, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.28/bin.28.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.28/bin.28.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.28/bin.28.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 5
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17063.89it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.28/bin.28.faa
Total: 641, Completed: 453, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 18
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11406.86it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.3/bin.3.faa
Total: 641, Completed: 454, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.39/bin.39.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.39/bin.39.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.39/bin.39.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 228
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15218.81it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C2/bin.39/bin.39.faa
Total: 641, Completed: 455, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.46/bin.46.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.46/bin.46.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.46/bin.46.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12945.38it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.46/bin.46.faa
Total: 641, Completed: 456, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 249
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56073.58it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.8/bin.8.faa
Total: 641, Completed: 457, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.38/bin.38.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.38/bin.38.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.38/bin.38.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13408.90it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.38/bin.38.faa
Total: 641, Completed: 458, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 194
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57772.78it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.15/bin.15.faa
Total: 641, Completed: 459, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57614.07it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.4/bin.4.faa
Total: 641, Completed: 460, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 298
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 41160.98it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.1/bin.1.faa
Total: 641, Completed: 461, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.40/bin.40.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.40/bin.40.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.40/bin.40.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 58
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 24216.54it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.40/bin.40.faa
Total: 641, Completed: 462, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 288
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9478.65it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.19/bin.19.faa
Total: 641, Completed: 463, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12087.33it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.13/bin.13.faa
Total: 641, Completed: 464, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 645
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58092.85it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.3/bin.3.faa
Total: 641, Completed: 465, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.36/bin.36.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.36/bin.36.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.36/bin.36.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16898.89it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.36/bin.36.faa
Total: 641, Completed: 466, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 127
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57299.23it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.11/bin.11.faa
Total: 641, Completed: 467, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.31/bin.31.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.31/bin.31.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.31/bin.31.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 24
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53704.28it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.31/bin.31.faa
Total: 641, Completed: 468, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.23/bin.23.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.23/bin.23.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.23/bin.23.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 340
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9438.13it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.23/bin.23.faa
Total: 641, Completed: 469, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 380
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8361.85it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.6/bin.6.faa
Total: 641, Completed: 470, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 180
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58416.49it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.24/bin.24.faa
Total: 641, Completed: 471, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 193
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13697.92it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.14/bin.14.faa
Total: 641, Completed: 472, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 798
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 18379.95it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C9/bin.17/bin.17.faa
Total: 641, Completed: 473, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20126.22it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.8/bin.8.faa
Total: 641, Completed: 474, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7616.31it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.15/bin.15.faa
Total: 641, Completed: 475, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1058
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 24774.39it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.4/bin.4.faa
Total: 641, Completed: 476, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13508.23it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.9/bin.9.faa
Total: 641, Completed: 477, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 294
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 49991.70it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.18/bin.18.faa
Total: 641, Completed: 478, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 317
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21868.11it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.22/bin.22.faa
Total: 641, Completed: 479, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 638
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17757.43it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.1/bin.1.faa
Total: 641, Completed: 480, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 683
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14985.01it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.12/bin.12.faa
Total: 641, Completed: 481, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 10
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14523.21it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.3/bin.3.faa
Total: 641, Completed: 482, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 81
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56756.48it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.25/bin.25.faa
Total: 641, Completed: 483, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 607
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58826.14it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F10/bin.20/bin.20.faa
Total: 641, Completed: 484, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.37/bin.37.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.37/bin.37.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.37/bin.37.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 47339.77it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.37/bin.37.faa
Total: 641, Completed: 485, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 682
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53704.28it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.15/bin.15.faa
Total: 641, Completed: 486, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 107
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20908.79it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.10/bin.10.faa
Total: 641, Completed: 487, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.50/bin.50.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.50/bin.50.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.50/bin.50.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.50.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 61
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57065.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.50/bin.50.faa
Total: 641, Completed: 488, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.51/bin.51.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.51/bin.51.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.51/bin.51.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14942.30it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.51/bin.51.faa
Total: 641, Completed: 489, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51212.50it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.26/bin.26.faa
Total: 641, Completed: 490, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.44/bin.44.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.44/bin.44.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.44/bin.44.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.44.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 464
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13294.15it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.44/bin.44.faa
Total: 641, Completed: 491, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.48/bin.48.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.48/bin.48.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.48/bin.48.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 754
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14650.03it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.48/bin.48.faa
Total: 641, Completed: 492, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.21/bin.21.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.21/bin.21.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.21/bin.21.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 72
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20068.44it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.21/bin.21.faa
Total: 641, Completed: 493, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.31/bin.31.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.31/bin.31.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.31/bin.31.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 834
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57614.07it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B12/bin.31/bin.31.faa
Total: 641, Completed: 494, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 32
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7601.13it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.15/bin.15.faa
Total: 641, Completed: 495, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 106
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54189.97it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.4/bin.4.faa
Total: 641, Completed: 496, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 10
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13516.93it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.9/bin.9.faa
Total: 641, Completed: 497, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 648
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 23763.76it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.18/bin.18.faa
Total: 641, Completed: 498, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 59747.92it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.19/bin.19.faa
Total: 641, Completed: 499, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.21/bin.21.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.21/bin.21.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.21/bin.21.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 22894.67it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.21/bin.21.faa
Total: 641, Completed: 500, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57614.07it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.25/bin.25.faa
Total: 641, Completed: 501, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.23/bin.23.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.23/bin.23.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.23/bin.23.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 110
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56223.91it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.23/bin.23.faa
Total: 641, Completed: 502, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 106
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16396.81it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A11/bin.14/bin.14.faa
Total: 641, Completed: 503, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 159
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7068.26it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.9/bin.9.faa
Total: 641, Completed: 504, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 292
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 36314.32it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.18/bin.18.faa
Total: 641, Completed: 505, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.40/bin.40.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.40/bin.40.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.40/bin.40.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.40.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 683
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58661.59it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.40/bin.40.faa
Total: 641, Completed: 506, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 524
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 59325.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.19/bin.19.faa
Total: 641, Completed: 507, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53980.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.2/bin.2.faa
Total: 641, Completed: 508, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 18
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8497.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.25/bin.25.faa
Total: 641, Completed: 509, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.23/bin.23.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.23/bin.23.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.23/bin.23.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 22782.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.23/bin.23.faa
Total: 641, Completed: 510, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17077.79it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.20/bin.20.faa
Total: 641, Completed: 511, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 82
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17008.53it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F7/bin.17/bin.17.faa
Total: 641, Completed: 512, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H5/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H5/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H5/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 631
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58416.49it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H5/bin.1/bin.1.faa
Total: 641, Completed: 513, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H5/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H5/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H5/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 11
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15803.71it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H5/bin.2/bin.2.faa
Total: 641, Completed: 514, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51087.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.5/bin.5.faa
Total: 641, Completed: 515, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 527
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14899.84it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.16/bin.16.faa
Total: 641, Completed: 516, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7710.12it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.11/bin.11.faa
Total: 641, Completed: 517, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 107
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56833.39it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.14/bin.14.faa
Total: 641, Completed: 518, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12383.54it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E7/bin.17/bin.17.faa
Total: 641, Completed: 519, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 295
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16804.10it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.9/bin.9.faa
Total: 641, Completed: 520, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 190
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13005.59it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.10/bin.10.faa
Total: 641, Completed: 521, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53704.28it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.13/bin.13.faa
Total: 641, Completed: 522, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 440
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16156.80it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.3/bin.3.faa
Total: 641, Completed: 523, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 187
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15984.39it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.11/bin.11.faa
Total: 641, Completed: 524, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 292
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14403.52it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E12/bin.6/bin.6.faa
Total: 641, Completed: 525, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C12/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C12/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C12/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21258.51it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C12/bin.10/bin.10.faa
Total: 641, Completed: 526, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C12/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C12/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C12/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 50
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57614.07it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C12/bin.12/bin.12.faa
Total: 641, Completed: 527, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 643
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8468.21it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.5/bin.5.faa
Total: 641, Completed: 528, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16750.42it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.18/bin.18.faa
Total: 641, Completed: 529, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14836.59it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.25/bin.25.faa
Total: 641, Completed: 530, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 11
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11755.34it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.6/bin.6.faa
Total: 641, Completed: 531, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 193
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 22745.68it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B1/bin.24/bin.24.faa
Total: 641, Completed: 532, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A4/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A4/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A4/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 505
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55627.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A4/bin.9/bin.9.faa
Total: 641, Completed: 533, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.46/bin.46.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.46/bin.46.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.46/bin.46.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.46.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 50717.10it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.46/bin.46.faa
Total: 641, Completed: 534, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 522
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15887.52it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.4/bin.4.faa
Total: 641, Completed: 535, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 58
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57932.38it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.22/bin.22.faa
Total: 641, Completed: 536, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.51/bin.51.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.51/bin.51.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.51/bin.51.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.51.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 215
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20174.62it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.51/bin.51.faa
Total: 641, Completed: 537, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11706.12it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.26/bin.26.faa
Total: 641, Completed: 538, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.48/bin.48.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.48/bin.48.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.48/bin.48.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.48.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 136
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 60787.01it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.48/bin.48.faa
Total: 641, Completed: 539, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.31/bin.31.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.31/bin.31.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.31/bin.31.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 7
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 58416.49it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.31/bin.31.faa
Total: 641, Completed: 540, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 5
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10043.83it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.24/bin.24.faa
Total: 641, Completed: 541, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.34/bin.34.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.34/bin.34.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.34/bin.34.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 193
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57535.03it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.34/bin.34.faa
Total: 641, Completed: 542, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 110
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 5331.52it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C3/bin.17/bin.17.faa
Total: 641, Completed: 543, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 92
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 43919.41it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.7/bin.7.faa
Total: 641, Completed: 544, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 194
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13477.84it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.13/bin.13.faa
Total: 641, Completed: 545, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 669
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14947.63it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.12/bin.12.faa
Total: 641, Completed: 546, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 271
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7157.52it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A3/bin.2/bin.2.faa
Total: 641, Completed: 547, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 33
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 51087.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.5/bin.5.faa
Total: 641, Completed: 548, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 2
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 63072.24it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.7/bin.7.faa
Total: 641, Completed: 549, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.37/bin.37.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.37/bin.37.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.37/bin.37.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.37.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 90
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57693.31it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.37/bin.37.faa
Total: 641, Completed: 550, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 46
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57693.31it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.4/bin.4.faa
Total: 641, Completed: 551, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11824.93it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.2/bin.2.faa
Total: 641, Completed: 552, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 631
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56450.93it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.3/bin.3.faa
Total: 641, Completed: 553, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.21/bin.21.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.21/bin.21.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.21/bin.21.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 36
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 18244.04it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.21/bin.21.faa
Total: 641, Completed: 554, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 20
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52560.20it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.25/bin.25.faa
Total: 641, Completed: 555, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 23
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 60699.04it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H10/bin.17/bin.17.faa
Total: 641, Completed: 556, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.5/bin.5.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.5/bin.5.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.5/bin.5.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.5.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1258
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 61500.06it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.5/bin.5.faa
Total: 641, Completed: 557, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 176
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10785.04it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.8/bin.8.faa
Total: 641, Completed: 558, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 677
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14004.35it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.16/bin.16.faa
Total: 641, Completed: 559, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 301
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17697.49it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.1/bin.1.faa
Total: 641, Completed: 560, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 839
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13609.03it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.26/bin.26.faa
Total: 641, Completed: 561, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.19/bin.19.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.19/bin.19.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.19/bin.19.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.19.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 126
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57299.23it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.19/bin.19.faa
Total: 641, Completed: 562, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 101
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14359.14it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.13/bin.13.faa
Total: 641, Completed: 563, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 115
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19328.59it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.3/bin.3.faa
Total: 641, Completed: 564, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 99
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 8943.08it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.6/bin.6.faa
Total: 641, Completed: 565, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 14
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12242.57it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.14/bin.14.faa
Total: 641, Completed: 566, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 646
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15358.13it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G7/bin.17/bin.17.faa
Total: 641, Completed: 567, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 798
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11589.68it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.8/bin.8.faa
Total: 641, Completed: 568, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 22745.68it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.18/bin.18.faa
Total: 641, Completed: 569, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.22/bin.22.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.22/bin.22.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.22/bin.22.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.22.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 600
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 60004.35it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.22/bin.22.faa
Total: 641, Completed: 570, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 774
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56223.91it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.1/bin.1.faa
Total: 641, Completed: 571, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1053
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.002s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56223.91it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.13/bin.13.faa
Total: 641, Completed: 572, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.21/bin.21.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.21/bin.21.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.21/bin.21.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.21.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 5
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 61320.23it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.21/bin.21.faa
Total: 641, Completed: 573, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.25/bin.25.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.25/bin.25.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.25/bin.25.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.25.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 248
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11605.71it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.25/bin.25.faa
Total: 641, Completed: 574, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9915.61it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1B5/bin.20/bin.20.faa
Total: 641, Completed: 575, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 99
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52958.38it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.15/bin.15.faa
Total: 641, Completed: 576, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 215
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 60176.53it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.4/bin.4.faa
Total: 641, Completed: 577, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.30/bin.30.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.30/bin.30.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.30/bin.30.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.30.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 272
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 6743.25it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.30/bin.30.faa
Total: 641, Completed: 578, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 131
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13792.52it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.12/bin.12.faa
Total: 641, Completed: 579, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 309
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11644.38it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.2/bin.2.faa
Total: 641, Completed: 580, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 609
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 12278.41it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1G8/bin.6/bin.6.faa
Total: 641, Completed: 581, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H6/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H6/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H6/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 69
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 46091.25it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H6/bin.4/bin.4.faa
Total: 641, Completed: 582, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H6/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H6/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H6/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 631
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 59158.03it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H6/bin.10/bin.10.faa
Total: 641, Completed: 583, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H2/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H2/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H2/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 475
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17084.74it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H2/bin.2/bin.2.faa
Total: 641, Completed: 584, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H2/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H2/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H2/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1938
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7602.51it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H2/bin.3/bin.3.faa
Total: 641, Completed: 585, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.8/bin.8.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.8/bin.8.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.8/bin.8.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.8.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 532
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 20805.08it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.8/bin.8.faa
Total: 641, Completed: 586, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 193
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 14438.22it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.9/bin.9.faa
Total: 641, Completed: 587, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 35
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21312.52it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.2/bin.2.faa
Total: 641, Completed: 588, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 308
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10351.19it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E2/bin.11/bin.11.faa
Total: 641, Completed: 589, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.38/bin.38.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.38/bin.38.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.38/bin.38.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15274.23it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.38/bin.38.faa
Total: 641, Completed: 590, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 385
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55775.32it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.16/bin.16.faa
Total: 641, Completed: 591, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 285
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53159.75it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.9/bin.9.faa
Total: 641, Completed: 592, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 29
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10496.26it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.10/bin.10.faa
Total: 641, Completed: 593, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 7
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16824.32it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.26/bin.26.faa
Total: 641, Completed: 594, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.45/bin.45.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.45/bin.45.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.45/bin.45.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.45.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 526
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17810.21it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.45/bin.45.faa
Total: 641, Completed: 595, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.52/bin.52.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.52/bin.52.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.52/bin.52.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.52.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 107
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55480.21it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.52/bin.52.faa
Total: 641, Completed: 596, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.54/bin.54.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.54/bin.54.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.54/bin.54.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.54.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 257
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 13260.52it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.54/bin.54.faa
Total: 641, Completed: 597, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.28/bin.28.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.28/bin.28.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.28/bin.28.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.28.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 158
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 18600.02it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.28/bin.28.faa
Total: 641, Completed: 598, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.61/bin.61.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.61/bin.61.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.61/bin.61.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.61.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 5
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53704.28it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.61/bin.61.faa
Total: 641, Completed: 599, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.11/bin.11.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.11/bin.11.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.11/bin.11.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.11.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 12
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 9536.84it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.11/bin.11.faa
Total: 641, Completed: 600, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.31/bin.31.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.31/bin.31.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.31/bin.31.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.31.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 617
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17260.51it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.31/bin.31.faa
Total: 641, Completed: 601, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 62977.54it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.24/bin.24.faa
Total: 641, Completed: 602, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.34/bin.34.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.34/bin.34.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.34/bin.34.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 54542.31it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.34/bin.34.faa
Total: 641, Completed: 603, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.39/bin.39.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.39/bin.39.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.39/bin.39.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.39.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 603
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7518.02it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.39/bin.39.faa
Total: 641, Completed: 604, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.55/bin.55.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.55/bin.55.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.55/bin.55.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.55.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 55
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10245.00it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.55/bin.55.faa
Total: 641, Completed: 605, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 69
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17161.64it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1D4/bin.17/bin.17.faa
Total: 641, Completed: 606, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 243
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 46500.04it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.15/bin.15.faa
Total: 641, Completed: 607, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.9/bin.9.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.9/bin.9.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.9/bin.9.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.9.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 247
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17586.18it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.9/bin.9.faa
Total: 641, Completed: 608, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 107
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 63840.24it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.10/bin.10.faa
Total: 641, Completed: 609, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 573
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 15136.43it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.18/bin.18.faa
Total: 641, Completed: 610, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.1/bin.1.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.1/bin.1.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.1/bin.1.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.1.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 186
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52298.05it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.1/bin.1.faa
Total: 641, Completed: 611, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 292
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 24774.39it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.3/bin.3.faa
Total: 641, Completed: 612, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55701.25it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.6/bin.6.faa
Total: 641, Completed: 613, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 295
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 22574.29it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E11/bin.14/bin.14.faa
Total: 641, Completed: 614, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.38/bin.38.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.38/bin.38.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.38/bin.38.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.38.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 10656.26it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.38/bin.38.faa
Total: 641, Completed: 615, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 13
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 36663.50it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.18/bin.18.faa
Total: 641, Completed: 616, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.26/bin.26.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.26/bin.26.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.26/bin.26.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.26.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 3
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 49228.92it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.26/bin.26.faa
Total: 641, Completed: 617, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 364
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 52298.05it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.13/bin.13.faa
Total: 641, Completed: 618, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.23/bin.23.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.23/bin.23.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.23/bin.23.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.23.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 66
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 53092.46it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.23/bin.23.faa
Total: 641, Completed: 619, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.20/bin.20.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.20/bin.20.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.20/bin.20.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.20.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 139
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56375.05it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.20/bin.20.faa
Total: 641, Completed: 620, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.34/bin.34.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.34/bin.34.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.34/bin.34.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.34.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 16
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 49286.77it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.34/bin.34.faa
Total: 641, Completed: 621, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 59
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 49872.82it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C10/bin.14/bin.14.faa
Total: 641, Completed: 622, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.13/bin.13.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.13/bin.13.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.13/bin.13.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.13.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 285
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 50717.10it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.13/bin.13.faa
Total: 641, Completed: 623, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 24
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 6539.30it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.12/bin.12.faa
Total: 641, Completed: 624, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.2/bin.2.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.2/bin.2.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.2/bin.2.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.2.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 631
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 57535.03it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.2/bin.2.faa
Total: 641, Completed: 625, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.3/bin.3.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.3/bin.3.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.3/bin.3.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.3.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 6
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55480.21it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.3/bin.3.faa
Total: 641, Completed: 626, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.17/bin.17.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.17/bin.17.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.17/bin.17.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.17.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 247
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 7742.85it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1E4/bin.17/bin.17.faa
Total: 641, Completed: 627, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.7/bin.7.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.7/bin.7.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.7/bin.7.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.7.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 790
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 16301.22it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.7/bin.7.faa
Total: 641, Completed: 628, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.15/bin.15.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.15/bin.15.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.15/bin.15.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.15.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 4
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 18550.66it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.15/bin.15.faa
Total: 641, Completed: 629, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.10/bin.10.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.10/bin.10.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.10/bin.10.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.10.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 566
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 49171.21it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.10/bin.10.faa
Total: 641, Completed: 630, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.6/bin.6.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.6/bin.6.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.6/bin.6.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.6.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 531
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55043.36it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.6/bin.6.faa
Total: 641, Completed: 631, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 31
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 19213.49it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1F4/bin.14/bin.14.faa
Total: 641, Completed: 632, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.4/bin.4.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.4/bin.4.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.4/bin.4.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.4.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 59
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56603.29it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.4/bin.4.faa
Total: 641, Completed: 633, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.18/bin.18.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.18/bin.18.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.18/bin.18.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.18.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 11308.45it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.18/bin.18.faa
Total: 641, Completed: 634, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 0
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 61141.46it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.12/bin.12.faa
Total: 641, Completed: 635, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.36/bin.36.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.36/bin.36.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.36/bin.36.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.36.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 159
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 43106.93it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1C11/bin.36/bin.36.faa
Total: 641, Completed: 636, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.16/bin.16.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.16/bin.16.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.16/bin.16.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.16.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 669
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 17682.56it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.16/bin.16.faa
Total: 641, Completed: 637, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.12/bin.12.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.12/bin.12.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.12/bin.12.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.12.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 1
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 56375.05it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.12/bin.12.faa
Total: 641, Completed: 638, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.24/bin.24.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.24/bin.24.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.24/bin.24.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.24.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 55
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 55627.37it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.24/bin.24.faa
Total: 641, Completed: 639, Failed: 1
Running: deeparg predict --model LS --type prot --input /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.14/bin.14.faa --output /home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14

INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/bin/linux-x86_64/diamond "HTTP/1.1 302 Found"
INFO:root:Using DIAMOND: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond (diamond version 2.1.24)
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.dmnd "HTTP/1.1 302 Found"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/database/features.gene.length "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fdatabase%2Ffeatures.gene.length "HTTP/1.1 200 OK"
INFO:root:DIAMOND blastp alignment
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond blastp -q '/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.14/bin.14.faa' -d /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS/database/features -k 1000 --id 50 --sensitive -e 1e-10 -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align'
INFO:root:Input:/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.14/bin.14.faa output:/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14 model: deepARG_LS, Input type: blastp
INFO:root:parsing output file ['/home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond', 'view', '-a', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa', '-o', '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv']
INFO:root:Running: /home/ubuntu/.cache/huggingface/hub/models--gaarangoa--deeparg/snapshots/07d2eaa78502f41725c4222de1288b8b2f0d6259/bin/linux-x86_64/diamond view -a '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa' -o '/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/bin.14.align.daa.tsv'
diamond v2.1.24.178 (C) Max Planck Society for the Advancement of Science, Benjamin J. Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 24
Loading subject IDs...  [0s]
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 12279
DB sequences used = 603
DB letters = 5088898
#Target sequences to report alignments for: 25
Generating output...  [0.001s]
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/config.json "HTTP/1.1 307 Temporary Redirect"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/gaarangoa/deeparg/07d2eaa78502f41725c4222de1288b8b2f0d6259/LS%2Fconfig.json "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD https://huggingface.co/gaarangoa/deeparg/resolve/main/LS/model.safetensors "HTTP/1.1 302 Found"
Loading weights: 100%|██████████| 10/10 [00:00<00:00, 21509.25it/s]

COMPLETED: /home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1H12/bin.14/bin.14.faa
Total: 641, Completed: 640, Failed: 1

In [7]:
print(f"Processing completed. Total: {total}, Completed: {completed}, Failed: {filed}")
if filed_files:
    print("Failed files:")
    for f in filed_files:
        print(f)

Processing completed. Total: 641, Completed: 640, Failed: 1
Failed files:
/home/ubuntu/projects/biodata/DNA-BERT/data/raw/Wetland Metagenome Assembled Genomes/S1A1/bin.3/._bin.3.faa

In [13]:
OUTPUT_DIR = Path(OUTPUT_DIR)
SUMMARY_DIR = OUTPUT_DIR / "_summary"
SUMMARY_DIR.mkdir(parents=True, exist_ok=True)

In [14]:
def read_deeparg_file(path):
    if path.stat().st_size == 0:
        return pd.DataFrame()

    try:
        return pd.read_csv(path, sep="\t")
    except Exception:
        return pd.read_csv(path, sep="\t", engine="python")

In [15]:
def find_col(df, candidates):
    lower_map = {c.lower(): c for c in df.columns}
    for c in candidates:
        if c.lower() in lower_map:
            return lower_map[c.lower()]
    return None

In [16]:
rows = []
all_arg_rows = []

arg_files = sorted(OUTPUT_DIR.rglob("*.mapping.ARG"))

for arg_file in arg_files:
    sample = arg_file.name.replace(".mapping.ARG", "")
    potential_file = arg_file.with_name(sample + ".mapping.potential.ARG")
    align_file = arg_file.with_name(sample + ".align.daa.tsv")

    arg_df = read_deeparg_file(arg_file)
    potential_df = read_deeparg_file(potential_file) if potential_file.exists() else pd.DataFrame()

    class_col = find_col(arg_df, ["predicted_ARG-class", "predicted_arg-class", "arg_class", "ARG-class"])

    gene_col = find_col(arg_df, ["read_id", "query", "qseqid", "sequence", "gene", "ORF_ID"])

    best_hit_col = find_col(arg_df, ["best-hit", "best_hit", "sseqid", "ARG", "arg"])

    prob_col = find_col(arg_df, ["probability", "prob", "score"])

    n_args = len(arg_df)
    n_potential_args = len(potential_df)

    if class_col and n_args > 0:
        class_counts = arg_df[class_col].value_counts()
        top_class = class_counts.index[0]
        top_class_count = int(class_counts.iloc[0])
        n_classes = int(arg_df[class_col].nunique())
    else:
        top_class = None
        top_class_count = 0
        n_classes = 0

    rows.append(
        {
            "sample": sample,
            "has_ARG": n_args > 0,
            "n_ARGs": n_args,
            "n_potential_ARGs": n_potential_args,
            "n_ARG_classes": n_classes,
            "top_ARG_class": top_class,
            "top_ARG_class_count": top_class_count,
            "arg_file": str(arg_file),
            "potential_arg_file_exists": potential_file.exists(),
            "align_file_exists": align_file.exists(),
        }
    )

    if n_args > 0:
        tmp = arg_df.copy()
        tmp["sample"] = sample
        tmp["arg_file"] = str(arg_file)

        if class_col:
            tmp["deeparg_label"] = tmp[class_col]
        else:
            tmp["deeparg_label"] = "ARG"

        if gene_col:
            tmp["sequence_id"] = tmp[gene_col]
        else:
            tmp["sequence_id"] = tmp.index.astype(str)

        if best_hit_col:
            tmp["deeparg_best_hit"] = tmp[best_hit_col]
        else:
            tmp["deeparg_best_hit"] = None

        if prob_col:
            tmp["deeparg_score"] = tmp[prob_col]
        else:
            tmp["deeparg_score"] = None

        all_arg_rows.append(tmp)


summary_df = pd.DataFrame(rows)

if all_arg_rows:
    all_args_df = pd.concat(all_arg_rows, ignore_index=True)
else:
    all_args_df = pd.DataFrame()


summary_df.to_csv(SUMMARY_DIR / "deeparg_file_summary.tsv", sep="\t", index=False)
all_args_df.to_csv(SUMMARY_DIR / "deeparg_all_positive_ARGs.tsv", sep="\t", index=False)

In [17]:
# Confusion-matrix-style table:
# rows = genome/bin/sample
# columns = ARG class
# values = count of ARGs in that sample/class
if not all_args_df.empty and "deeparg_label" in all_args_df.columns:
    class_matrix = pd.pivot_table(all_args_df, index="sample", columns="deeparg_label", values="sequence_id", aggfunc="count", fill_value=0)

    class_matrix.to_csv(SUMMARY_DIR / "deeparg_ARG_class_count_matrix.tsv", sep="\t")

    presence_matrix = (class_matrix > 0).astype(int)
    presence_matrix.to_csv(SUMMARY_DIR / "deeparg_ARG_class_presence_matrix.tsv", sep="\t")
else:
    class_matrix = pd.DataFrame()
    presence_matrix = pd.DataFrame()

In [18]:
# Dataset-level story table
dataset_story = {
    "n_samples_scanned": len(summary_df),
    "n_samples_with_ARGs": int(summary_df["has_ARG"].sum()) if not summary_df.empty else 0,
    "n_samples_without_ARGs": int((~summary_df["has_ARG"]).sum()) if not summary_df.empty else 0,
    "total_ARG_hits": int(summary_df["n_ARGs"].sum()) if not summary_df.empty else 0,
    "total_potential_ARG_hits": int(summary_df["n_potential_ARGs"].sum()) if not summary_df.empty else 0,
    "mean_ARGs_per_sample": float(summary_df["n_ARGs"].mean()) if not summary_df.empty else 0,
    "median_ARGs_per_sample": float(summary_df["n_ARGs"].median()) if not summary_df.empty else 0,
    "max_ARGs_in_one_sample": int(summary_df["n_ARGs"].max()) if not summary_df.empty else 0,
}

pd.DataFrame([dataset_story]).to_csv(SUMMARY_DIR / "deeparg_dataset_story.tsv", sep="\t", index=False)

In [19]:
# Positive file list
positive_files = summary_df[summary_df["has_ARG"]].copy()
positive_files.to_csv(SUMMARY_DIR / "deeparg_files_with_ARGs.tsv", sep="\t", index=False)

In [37]:
dfs = {os.path.join(SUMMARY_DIR, f): pd.read_csv(os.path.join(SUMMARY_DIR, f), sep="\t") for f in os.listdir(SUMMARY_DIR)}

In [42]:
list(dfs.values())[0].T

                                   0
n_samples_scanned          63.000000
n_samples_with_ARGs        29.000000
n_samples_without_ARGs     34.000000
total_ARG_hits             80.000000
total_potential_ARG_hits  142.000000
mean_ARGs_per_sample        1.269841
median_ARGs_per_sample      0.000000
max_ARGs_in_one_sample      8.000000

In [51]:
for i, (path, df) in enumerate(dfs.items()):
    if i == 0:
        continue
    print(f"File: {os.path.basename(path)}")
    print(f"Shape: {df.shape}")
    if i == 2:  # For the class count matrix, show the full table
        print("non zero entries:", df[df.n_ARGs > 0].shape[0])
        print("non zero potential:", df[df.n_potential_ARGs > 0].shape[0])
        print("non zero non overlapping potential only files:", df[(df.n_ARGs == 0) & (df.n_potential_ARGs > 0)].shape[0])
    # print(df.info())
    display(df.head())

    print("\n\n")

File: deeparg_files_with_ARGs.tsv
Shape: (29, 10)

,sample,has_ARG,n_ARGs,n_potential_ARGs,n_ARG_classes,top_ARG_class,top_ARG_class_count,arg_file,potential_arg_file_exists,align_file_exists
0,bin.1,True,1,2,1,bacitracin,1,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,True,True
1,bin.10,True,6,3,5,multidrug,2,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,True,True
2,bin.14,True,7,16,4,multidrug,4,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,True,True
3,bin.16,True,1,2,1,multidrug,1,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,True,True
4,bin.19,True,1,2,1,MLS,1,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,True,True

File: deeparg_file_summary.tsv
Shape: (63, 10)
non zero entries: 29
non zero potential: 44
non zero non overlapping potential only files: 20

,sample,has_ARG,n_ARGs,n_potential_ARGs,n_ARG_classes,top_ARG_class,top_ARG_class_count,arg_file,potential_arg_file_exists,align_file_exists
0,bin.1,True,1,2,1,bacitracin,1,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,True,True
1,bin.10,True,6,3,5,multidrug,2,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,True,True
2,bin.11,False,0,0,0,NaN,0,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,True,True
3,bin.12,False,0,2,0,NaN,0,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,True,True
4,bin.13,False,0,2,0,NaN,0,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,True,True

File: deeparg_ARG_class_presence_matrix.tsv
Shape: (29, 10)

,sample,MLS,aminoglycoside,bacitracin,fosmidomycin,multidrug,peptide,phenicol,tetracycline,unclassified
0,bin.1,0,0,1,0,0,0,0,0,0
1,bin.10,0,1,1,1,1,1,0,0,0
2,bin.14,0,1,1,0,1,0,0,0,1
3,bin.16,0,0,0,0,1,0,0,0,0
4,bin.19,1,0,0,0,0,0,0,0,0

File: deeparg_all_positive_ARGs.tsv
Shape: (80, 18)

,#ARG,query-start,query-end,read_id,predicted_ARG-class,best-hit,probability,identity,alignment-length,alignment-bitscore,alignment-evalue,counts,sample,arg_file,deeparg_label,sequence_id,deeparg_best_hit,deeparg_score
0,BACA,1,291,AAHDPPLL_01139,bacitracin,YP_584847|FEATURES|bacA|bacitracin|bacA,0.992063,67.5,295,388.0,2.090000e-137,1,bin.1,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,bacitracin,AAHDPPLL_01139,YP_584847|FEATURES|bacA|bacitracin|bacA,0.992063
1,ROSB,1,552,JHMMIFGA_00180,fosmidomycin,gi:896190680:ref:WP_049199932.1:|FEATURES|rosB...,0.999900,53.4,560,528.0,5.010000e-184,1,bin.10,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,fosmidomycin,JHMMIFGA_00180,gi:896190680:ref:WP_049199932.1:|FEATURES|rosB...,0.999900
2,BACA,1,276,JHMMIFGA_01068,bacitracin,ZP_04577926|FEATURES|bacA|bacitracin|bacA,0.995254,69.7,277,374.0,2.160000e-132,1,bin.10,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,bacitracin,JHMMIFGA_01068,ZP_04577926|FEATURES|bacA|bacitracin|bacA,0.995254
3,MEXE,40,374,JHMMIFGA_01080,multidrug,YP_406903|FEATURES|mexE|multidrug|mexE,0.999998,51.2,338,300.0,2.570000e-99,1,bin.10,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,multidrug,JHMMIFGA_01080,YP_406903|FEATURES|mexE|multidrug|mexE,0.999998
4,ACRB,1,1032,JHMMIFGA_01081,multidrug,gi:503341948:ref:WP_013576609.1:|FEATURES|acrB...,0.952842,55.5,1032,1080.0,0.000000e+00,1,bin.10,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,multidrug,JHMMIFGA_01081,gi:503341948:ref:WP_013576609.1:|FEATURES|acrB...,0.952842

File: deeparg_ARG_class_count_matrix.tsv
Shape: (29, 10)

,sample,MLS,aminoglycoside,bacitracin,fosmidomycin,multidrug,peptide,phenicol,tetracycline,unclassified
0,bin.1,0,0,1,0,0,0,0,0,0
1,bin.10,0,1,1,1,2,1,0,0,0
2,bin.14,0,1,1,0,4,0,0,0,1
3,bin.16,0,0,0,0,1,0,0,0,0
4,bin.19,1,0,0,0,0,0,0,0,0

In [ ]:
arg_df = dfs["deeparg_all_positive_ARGs.tsv"]

KeyError: 'deeparg_all_positive_ARGs.tsv'

In [ ]:
arg_df = dfs["/home/ubuntu/projects/biodata/DNA-BERT/data/interim/Wetland Metagenome Assembled Genomes/_summary/deeparg_all_positive_ARGs.tsv"]

In [59]:
arg_df.head()

,#ARG,query-start,query-end,read_id,predicted_ARG-class,best-hit,probability,identity,alignment-length,alignment-bitscore,alignment-evalue,counts,sample,arg_file,deeparg_label,sequence_id,deeparg_best_hit,deeparg_score
0,BACA,1,291,AAHDPPLL_01139,bacitracin,YP_584847|FEATURES|bacA|bacitracin|bacA,0.992063,67.5,295,388.0,2.090000e-137,1,bin.1,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,bacitracin,AAHDPPLL_01139,YP_584847|FEATURES|bacA|bacitracin|bacA,0.992063
1,ROSB,1,552,JHMMIFGA_00180,fosmidomycin,gi:896190680:ref:WP_049199932.1:|FEATURES|rosB...,0.999900,53.4,560,528.0,5.010000e-184,1,bin.10,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,fosmidomycin,JHMMIFGA_00180,gi:896190680:ref:WP_049199932.1:|FEATURES|rosB...,0.999900
2,BACA,1,276,JHMMIFGA_01068,bacitracin,ZP_04577926|FEATURES|bacA|bacitracin|bacA,0.995254,69.7,277,374.0,2.160000e-132,1,bin.10,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,bacitracin,JHMMIFGA_01068,ZP_04577926|FEATURES|bacA|bacitracin|bacA,0.995254
3,MEXE,40,374,JHMMIFGA_01080,multidrug,YP_406903|FEATURES|mexE|multidrug|mexE,0.999998,51.2,338,300.0,2.570000e-99,1,bin.10,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,multidrug,JHMMIFGA_01080,YP_406903|FEATURES|mexE|multidrug|mexE,0.999998
4,ACRB,1,1032,JHMMIFGA_01081,multidrug,gi:503341948:ref:WP_013576609.1:|FEATURES|acrB...,0.952842,55.5,1032,1080.0,0.000000e+00,1,bin.10,/home/ubuntu/projects/biodata/DNA-BERT/data/in...,multidrug,JHMMIFGA_01081,gi:503341948:ref:WP_013576609.1:|FEATURES|acrB...,0.952842